name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/notecal
            git pull origin main
            cd /server
            bun install
            pm2 restart notecal-server || pm2 start --interpreter bun index.ts --name notecal-server
            pm2 save
